#!/usr/bin/env sh

green='\033[0;32m'
red='\033[0;31m'
NC='\033[0m' # No Color


# Check if git-flow is installed
command -v git-flow >/dev/null 2>&1 || {
        echo >&2 "${red}'git-flow' is required to be installed. Aborting...${NC}";
        echo "Please have a look at https://github.com/petervanderdoes/gitflow/wiki for installation instructions.";
        exit 1;
        }

echo "${green}Setting up git-flow with default settings...${NC}"

# Force-initialize git-flow with default settings
git-flow init -df

echo "${green}All finished. Happy hacking!${NC}"
