class LookupDict(dict):
    def __getitem__(self, key):
        return self.__dict__.get(key, None)

    def get(self, key, default=None):
        return self.__dict__.get(key, default)

_text_format = {
    0: 'moodle',
    1: 'html',
    2: 'plain',
    # don't know why format 3 is not defined. Documentation says nothing about it.
    4: 'markdown'
}


# maybe use gettext for different versions?
class JsonFieldNames:
    access_exception = 'accessexception'
    add_attempt = 'addattempt'
    apply_to_all = 'applytoall'
    area = 'area'
    assign_feedback_text = 'plugindata[assignfeedbackcomments_editor][text]'
    assign_feedback_format = 'plugindata[assignfeedbackcomments_editor][format]'
    assign_feedback_file = 'plugindata[files_filemanager]'
    assignment_id = 'assignmentid'
    assignment_ids = 'assignmentids[]'
    assignment = 'assignment'
    assignments = 'assignments'
    attempt_number = 'attemptnumber'
    author = 'author'
    before = 'before'
    capabilities = 'capabilities[]'
    course_module_id = 'cmid'
    configs = 'configs'
    contents = 'contents'
    course = 'course'
    course_id = 'courseid'
    course_ids = 'courseids[]'
    courses = 'courses'
    context_id = 'contextid'
    context_level = 'contextlevel'
    component = 'component'
    criteria_name = 'criterianame'
    criteria_value = 'criteriavalue'
    debug_info = 'debuginfo'
    due_date = 'duedate'
    description = 'description'
    description_format = 'descriptionformat'
    editor_fields = 'editorfields'
    enrolled_user_count = 'enrolledusercount'
    error_code = 'errorcode'
    exception = 'exception'
    file_area = 'filearea'
    file_areas = 'fileareas'
    file_name = 'filename'
    file_path = 'filepath'
    file_size = 'filesize'
    file_url = 'fileurl'
    files = 'files'
    format = 'format'
    full_name = 'fullname'
    grade = 'grade'
    grader = 'grader'
    grades = 'grades'
    group_id = 'groupid'
    groups = 'groups'
    id = 'id'
    id_number = 'idnumber'
    item = 'item'
    item_id = 'itemid'
    include_not_enrolled_courses = 'includenotenrolledcourses'
    indent = 'indent'
    instance = 'instance'
    instance_id = 'instanceid'
    invalid_parameter_exception = 'invalid_parameter_exception'
    invalid_response_exception = 'invalid_response_exception'
    invalid_response_exception_errorcode = 'invalidresponse'
    invalid_token = 'invalidtoken'
    is_dir = 'isdir'
    license = 'license'
    message = 'message'
    mime_type = "mimetype"
    modified = 'modified'
    modicon = 'modicon'
    modname = 'modname'
    modplural = 'modplural'
    modules = 'modules'
    moodle_exception = 'moodle_exception'
    moodle_ws_rest_format = 'moodlewsrestformat'
    name = 'name'
    no_permissions = 'nopermissions'
    options = 'options[{:d}][{}]'
    required_capability_exception = 'required_capability_exception'
    password = 'password'
    parents = 'parents'
    plugin = 'plugin'
    plugin_data_online_text = 'plugindata[onlinetext_editor][text]'
    plugin_data_online_text_format = 'plugindata[onlinetext_editor][format]'
    plugin_data_online_text_item_id = 'plugindata[onlinetext_editor][itemid]'
    plugin_data_submission_files_item_id = 'plugindata[files_filemanager]'
    plugins = 'plugins'
    roles = 'roles'
    role_id = 'roleid'
    service = 'service'
    short_name = 'shortname'
    since = 'since'
    sort_order = 'sortorder'
    status = 'status'
    sub_type = 'subtype'
    submissions = 'submissions'
    summary = 'summary'
    summary_format = 'summaryformat'
    team_submission = 'teamsubmission'
    text = 'text'
    time_created = 'timecreated'
    time_modified = 'timemodified'
    type = 'type'
    token = 'token'
    url = 'url'
    user_id = 'userid'
    user_name = 'username'
    users = 'users'
    value = 'value'
    visible = 'visible'
    warning_code = 'warningcode'
    warnings = 'warnings'
    workflow_state = 'workflowstate'
    ws_function = 'wsfunction'
    ws_token = 'wstoken'


text_format = LookupDict()

for number, fmt in _text_format.items():
    setattr(text_format, fmt, number)
